name: /home/monfre/Documents/PhD/score/env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - aom=3.3.0=h27087fc_1
  - blas=2.113=mkl
  - blas-devel=3.9.0=13_linux64_mkl
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py310h6acc77f_1003
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.3.18=h06a4308_0
  - certifi=2021.10.8=py310hff52083_1
  - cffi=1.15.0=py310h0fdd8cc_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cryptography=36.0.0=py310h9ce1e76_0
  - cudatoolkit=10.2.89=h8f6ccaa_10
  - cycler=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - ffmpeg=5.0.0=h594f047_1
  - fonttools=4.31.2=py310h5764c6d_0
  - freetype=2.11.0=h70c0345_0
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.15=he1e5248_0
  - gpy=1.10.0=py310h96516ba_2
  - icu=69.1=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - kiwisolver=1.4.0=py310hbf28c38_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_mkl
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_mkl
  - libdeflate=1.10=h7f98852_0
  - libdrm=2.4.109=h7f98852_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgfortran-ng=11.2.0=h69a702a_14
  - libgfortran5=11.2.0=h5c6108e_14
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f98852_0
  - liblapack=3.9.0=13_linux64_mkl
  - liblapacke=3.9.0=13_linux64_mkl
  - libnsl=2.0.0=h7f98852_0
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtasn1=4.18.0=h7f98852_0
  - libtiff=4.3.0=h542a066_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libva=2.14.0=h7f98852_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h166bdaf_1014
  - llvm-openmp=13.0.1=he0ac6c6_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.1=py310h23f4a51_0
  - mkl=2022.0.1=h8d4b97c_803
  - mkl-devel=2022.0.1=ha770c72_804
  - mkl-include=2022.0.1=h8d4b97c_803
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h9c3ff4c_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.22.3=py310h45f3432_0
  - openh264=2.1.1=h780b84a_0
  - openssl=3.0.2=h166bdaf_1
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py310hb5077e9_0
  - paramz=0.9.5=py_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pillow=9.0.1=py310h22f2fdc_0
  - pip=22.0.4=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pysocks=1.7.1=py310hff52083_4
  - python=3.10.4=h2660328_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.11.0=py3.10_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=pyhd8ed1ab_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py310h1246948_0
  - scipy=1.8.0=py310hea5193d_1
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=61.2.0=py310hff52083_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.38.0=hc218d9a_0
  - statsmodels=0.13.2=py310h96516ba_0
  - svt-av1=0.9.1=h27087fc_0
  - tbb=2021.5.0=h4bd325d_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.11.0=py310_cu102
  - torchvision=0.12.0=py310_cu102
  - typing_extensions=4.1.1=pyha770c72_0
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py310h6acc77f_0
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - cdt==0.5.23
    - gputil==1.4.0
    - igraph==0.9.9
    - networkx==2.7.1
    - texttable==1.6.4
    - tqdm==4.63.1
